"""Stable identifiers: never rename existing model classes or historical labels."""

DEFAULT_SEQUENCE = [
    "front_passenger_34",
    "front",
    "front_driver_34",
    "driver_profile",
    "rear_driver_34",
    "rear",
    "rear_passenger_34",
    "passenger_profile",
]
SHOT_CATALOG = [
    ("unknown", "Unassigned"),
    ("front_passenger_34", "Front passenger ¾"),
    ("front", "Front"),
    ("front_driver_34", "Front driver ¾"),
    ("driver_profile", "Driver profile"),
    ("rear_driver_34", "Rear driver ¾"),
    ("rear", "Rear"),
    ("rear_passenger_34", "Rear passenger ¾"),
    ("passenger_profile", "Passenger profile"),
    ("wheel", "Wheel"),
    ("headlight", "Headlight"),
    ("taillight", "Taillight"),
    ("front_360_driver", "Front 360, driver"),
    ("front_360_center", "Front 360, center"),
    ("front_360_passenger", "Front 360, passenger"),
    ("rear_360_passenger", "Rear 360, passenger"),
    ("rear_360_center", "Rear 360, center"),
    ("rear_360_driver", "Rear 360, driver"),
    ("driver_dashboard", "Driver-side dashboard"),
    ("passenger_dashboard", "Passenger-side dashboard"),
    ("sunroof", "Sunroof"),
    ("rear_seats", "Rear seats"),
    ("trunk", "Trunk"),
    ("driver_door_controls", "Driver's door controls"),
    ("driver_seat_controls", "Driver's seat controls"),
    ("steering_wheel", "Steering wheel"),
    ("steering_left", "Steering close-up, left"),
    ("steering_right", "Steering close-up, right"),
    ("odometer", "Odometer"),
    ("radio", "Radio"),
    ("climate_control", "Climate control"),
    ("shifter", "Shifter"),
    ("center_console", "Center console"),
    ("push_button_start", "Push-button start"),
    ("rear_view_camera", "Rear view camera"),
    ("usb_charger", "USB charger"),
    ("left_dashboard_controls", "Left of steering dashboard controls"),
    ("left_steering_knob", "Left steering control knob"),
    ("right_steering_knob", "Right steering control knob"),
    ("navigation_screen", "Navigation screen"),
    ("infotainment_screen", "Infotainment screen"),
    ("tire_tread", "Tire tread"),
    ("key_fob", "Key fob"),
    ("driver_door", "Driver's door"),
    ("logo", "Logo"),
    ("cockpit", "Cockpit"),
    ("engine", "Engine"),
    ("front_passenger_34_wheel_turned", "Front passenger ¾, wheel turned"),
    ("other", "Other"),
    # Retained for old records and models; no relabeling or retraining required.
    ("interior", "Interior (legacy)"),
    ("dashboard", "Dashboard (legacy)"),
    ("cargo", "Cargo (legacy)"),
    ("detail", "Detail (legacy)"),
]
QUALITY_KEYS = ["angle", "blur", "crop", "exposure", "saturation", "framing", "overall"]


def good_labels(shot_type="unknown"):
    return {"shot_type": shot_type, **dict.fromkeys(QUALITY_KEYS, "good"), "note": ""}
